version: '3.8'
services:
    auth_provider:
        build:
            context: .
            dockerfile: ./auth/Dockerfile
        container_name: auth_provider
        ports:
            - "3000:3000"
        env_file:
            - .env