version: '3.8'
services:
    db_manager:
        build:
            context: .
            dockerfile: ./db/Dockerfile
        container_name: wom_db_manager
        ports:
            - "3001:3001"
        env_file:
            - .env
        depends_on:
            - mongodb
    auth_provider:
        build:
            context: .
            dockerfile: ./auth/Dockerfile
        container_name: wom_auth_provider
        ports:
            - "3000:3000"
        env_file:
            - .env
        depends_on:
            - mongodb
    log:
        build:
            context: .
            dockerfile: ./log/Dockerfile
        container_name: wom_log
        ports:
            - "3002:3002"
        env_file:
            - .env
        depends_on:
            - mongodb
    mongodb:
        image: mongo:latest
        container_name: wom_mongo
        ports:
            - "27017:27017"
        env_file:
            - .env