version: '3'

services:
    db_manager:
        build:
            context: .
            dockerfile: ./db/Dockerfile
        container_name: wom_db_manager
        ports:
            - "3001:3001"
        env_file:
            - .env
