version: '3.8'
services:
    db_manager:
        build:
            context: .
            dockerfile: ./db/Dockerfile
        container_name: wom_db_manager
        ports:
            - "3001:3001"
        env_file:
            - .env
    auth_provider:
        build:
            context: .
            dockerfile: ./auth/Dockerfile
        container_name: auth_provider
        ports:
            - "3000:3000"
        env_file:
            - .env
